arrayConstructs : arrayConstructs.o
	g++ -std=c++17 -O3 -o arrayConstructs arrayConstructs.o 
arrayConstructs.o : arrayConstructs.cpp 
	g++ -c arrayConstructs.cpp
clean:	
	rm arrayConstructs arrayConstructs.o